# Generated by Django 3.1.4 on 2021-02-24 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('last_edited', models.DateField(auto_now=True)),
                ('doc_type', models.IntegerField(choices=[(1, 'Paper'), (2, 'Project')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('NS', 'Not Set'), ('BCT', 'Bachelor in Computer Engineering'), ('BCE', 'Bachelor in Civil Engineering')], default='NS', max_length=3)),
                ('academic_status', models.IntegerField(choices=[(1, 'Not Set'), (2, 'Studying'), (3, 'Completed'), (4, 'Teaching')], default=1)),
                ('description', models.TextField(max_length=500, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_on', models.DateField(auto_now=True)),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_people', to='portal.person')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_people', to='portal.person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='relationships',
            field=models.ManyToManyField(related_name='related_to', through='portal.Relationship', to='portal.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(null=True, upload_to='files/')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.article')),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.person')),
                ('to_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.article')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.person')),
                ('to_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='collaborators',
            field=models.ManyToManyField(related_name='collaborators', to='portal.Person'),
        ),
        migrations.AddField(
            model_name='article',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='portal.person'),
        ),
    ]
