# Generated by Django 3.1.4 on 2021-02-24 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='files',
            new_name='file',
        ),
    ]
