# Generated by Django 3.1.4 on 2021-02-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20210224_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='collaborators',
            field=models.ManyToManyField(related_name='collaborators', to='portal.Person'),
        ),
    ]
