# Generated by Django 3.0.8 on 2021-02-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20210208_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='followed_on',
            field=models.DateField(auto_now=True),
        ),
    ]
