# Generated by Django 3.1.4 on 2021-03-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20210225_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'verbose_name_plural': 'files'},
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
