# Generated by Django 3.0.8 on 2021-02-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_relationship_followed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='document',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
