# Generated by Django 3.1.4 on 2021-02-23 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_person_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='collaborators',
            field=models.ManyToManyField(related_name='collaborators', to='portal.Person'),
        ),
        migrations.AlterField(
            model_name='article',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='portal.person'),
        ),
    ]
