# Generated by Django 3.0.8 on 2021-02-08 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20210207_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Person'),
        ),
    ]
