# Generated by Django 3.0.8 on 2021-02-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='doc_type',
            field=models.IntegerField(choices=[(1, 'Paper'), (2, 'Project')], default=1),
        ),
    ]
